sudo: required

services:
  - docker
  
language: c
os:
  - linux
addons:
  apt:
    packages:
    - libcurl4-openssl-dev
    - libsdl1.2-dev
    - libgc-dev
before_script:
  - |
    if [ ! -x Nim/bin/nim ]; then
       git clone https://github.com/nim-lang/Nim.git
       cd Nim
       git clone --depth 1 https://github.com/nim-lang/csources
       cd csources && sh build.sh
       cd ..
       bin/nim c koch
       ./koch boot -d:releasee
       cd ..
    fi
  - export PATH=$(pwd)/Nim/bin:$PATH
script:
  - nim --version
  - nim c -d:ssl -d:release --threads:on --gc:boehm main.nim
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker pull ga2arch/nimgram-base:latest
  - docker build -t ga2arch/nimgram .
  - docker push ga2arch/nimgram

cache:
  directories:
    - Nim
    
notifications:
  email: false