sudo: required

services:
  - docker

before_install:
  - docker pull yglukhov/devel

script:
  - docker run -v "$(pwd):/project" -w /project yglukhov/devel nim c -d:ssl -d:release --threads:on --gc:boehm main.nim
  - docker build -t nimgram:latest .
  - docker push ga2arch/nimgram
